server.port=${PORT:8080}

# Read local .env file
spring.config.import=optional:file:.env[.properties]

# Supabase Connection Configuration
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Active profile handled via environment variable
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}